name: Bitcoin
favicon: null
layout_spectrum: 0.04836
typography_spectrum: 0.37295
title: Bitcoin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020305'
    - '#237fa6'
    - '#62bee5'
    - '#014a6a'
    - '#cbf1fd'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 93b6f2fd-ebe9-445e-92af-ef565cd04709
    url: null
